app:
    resource: '@AppBundle/Controller/'
    type: annotation

genus:
    path: /
    defaults: {_controller: AppBundle:Controller:genusController}

index:
    path: /produit
    defaults: {_controller: AppBundle:Controller:indexController}

admin:
    path: /admin
    defaults: {_controller: AppBundle:Controller:adminController}

test:
    path: /test
    defaults: {_controller: AppBundle:Controller:testController}


index:
    path: /testformulaire
    defaults: {_controller: AppBundle:Controller:FormController}

index:
    path: /products
    defaults: {_controller: AppBundle:Controller:ProductsController}